const gruppi = require('./gruppi/gruppi.service.js');
const cattedre = require('./cattedre/cattedre.service.js');
const corsi = require('./corsi/corsi.service.js');
const discipline = require('./discipline/discipline.service.js');
const membri = require('./membri/membri.service.js');
const orari = require('./orari/orari.service.js');
const orario = require('./orario/orario.service.js');
const ore = require('./ore/ore.service.js');
const oraricorsi = require('./oraricorsi/oraricorsi.service.js');
const orarigiorni = require('./orarigiorni/orarigiorni.service.js');
const rubrica = require('./rubrica/rubrica.service.js');
const sedi = require('./sedi/sedi.service.js');
const tipologie = require('./tipologie/tipologie.service.js');
const todo = require('./todo/todo.service.js');
const users = require('./users/users.service.js');
const conf = require('./conf/conf.service.js');
const reports = require('./reports/reports.service.js');
const labels = require('./labels/labels.service.js');
const descrizioni = require('./descrizioni/descrizioni.service.js');
module.exports = function () {
  const app = this; // eslint-disable-line no-unused-vars
  app.configure(gruppi);
  app.configure(cattedre);
  app.configure(corsi);
  app.configure(discipline);
  app.configure(membri);
  app.configure(orari);
  app.configure(orario);
  app.configure(ore);
  app.configure(oraricorsi);
  app.configure(orarigiorni);
  app.configure(rubrica);
  app.configure(sedi);
  app.configure(tipologie);
  app.configure(todo);
  app.configure(users);
  app.configure(conf);
  app.configure(labels);
  app.configure(descrizioni);
  app.configure(reports);
};
